#!/bin/bash
#Require inxi awk grep bc cpufrequtils cat echo
#Set max temp limit with 7 for ecart-type, replace min cpu freq with nominal and max cpu freq from constructor sheet
MAX_TEMP=63
TEMP_DELTA=$(echo "4 / 2" | bc -l)
MAX_TEMP_ROUTINE="$(echo "$MAX_TEMP + $TEMP_DELTA" | bc -l)"
MIN_TEMP_ROUTINE="$(echo "$MAX_TEMP - $TEMP_DELTA" | bc -l)"
MIN_CPU_FREQ=1.8
MAX_CPU_FREQ=2.9
ACTUAL_CPU_FREQ_SET="$(echo "$MAX_CPU_FREQ - (($MAX_CPU_FREQ - $MIN_CPU_FREQ) * 40 / 100)" | bc -l)"
WAIT=1
FREQ_DIFF=0.1
CORE=4
STEP=1
HOT=0

value=`echo "$MIN_CPU_FREQ * 1000000" | bc`

sudo cpufreq-set -c 1 -g powersave -u `echo "$value"`
sudo cpufreq-set -c 2 -g powersave -u `echo "$value"`
sudo cpufreq-set -c 0 -g powersave -u `echo "$value"`
sudo cpufreq-set -c 3 -g powersave -u `echo "$value"`

#launch after boot start time
sleep 60

while true; do a=1; done&

CPU_STRESS_PID="$(echo $!)"

while true
do
    TEMPS="$(inxi -F | grep Sensors)"
    TEMPS="$(echo "$TEMPS" | grep -o -P "[0-9]*\.{1}[0-9]*")"
    CPU="$(inxi -F | grep -A 1 "clock speeds")"
    CPU="$(echo "$CPU" | grep -o -P "\d* MHz")"
    CPU="$(echo "$CPU" | grep -o -P "\d*")"
    
    FREQ1="$(echo "$CPU" | awk 'NR>2{exit}NR>=2')"
    FREQ2="$(echo "$CPU" | awk 'NR>3{exit}NR>=3')"
    FREQ3="$(echo "$CPU" | awk 'NR>4{exit}NR>=4')"
    FREQ4="$(echo "$CPU" | awk 'NR>5{exit}NR>=5')"
    
    ACTUAL_CPU_FREQ="$(echo "($FREQ1 + $FREQ2 + $FREQ3 + $FREQ4) / 4" | bc)"
    CPU_TEMP="$(echo "$TEMPS" | awk 'NR>1{exit}NR>=1')"
    ACTUAL_TEMP=${CPU_TEMP:0:(TEMP_LEN-2)}
    READABLE_ACTUAL_CPU_FREQ_SET=$(echo "$ACTUAL_CPU_FREQ_SET * 1000" | bc -l)
    
    if [ $ACTUAL_TEMP -gt  $MAX_TEMP ]
    then
        if [[ $STEP -eq 1 && $HOT -eq 1 ]]
        then
            ACTUAL_CPU_FREQ_SET="$(echo "$ACTUAL_CPU_FREQ_SET - $FREQ_DIFF" | bc)"
        elif [ $STEP -eq 1 ]
        then
            HOT=1
        fi
        
        if [ $STEP -eq 2 ]
        then
            STEP=3
            MAX_CPU_FREQ=$(echo "$ACTUAL_CPU_FREQ_SET * 1000" | bc -l)
            kill $CPU_STRESS_PID
        fi
        
        if [ $(echo "$ACTUAL_TEMP > $MAX_TEMP_ROUTINE" | bc -l) -eq 1  ]
        then
            if [ $STEP -eq 3 ] && [ $(echo "$ACTUAL_CPU_FREQ > $MIN_CPU_FREQ" | bc -l) -eq 1 ]
            then
                if [ $(echo "$READABLE_ACTUAL_CPU_FREQ_SET > $MIN_CPU_FREQ" | bc -l) -eq 1 ]
                then
                    ACTUAL_CPU_FREQ_SET="$(echo "$ACTUAL_CPU_FREQ_SET - $FREQ_DIFF" | bc)"
                fi
            fi
        fi
    elif [ $ACTUAL_TEMP -lt $MAX_TEMP ]
    then
        if [ $HOT -eq 1 ]
        then
            MIN_CPU_FREQ=$(echo "$ACTUAL_CPU_FREQ_SET * 1000 - 1" | bc -l)
            STEP=2
            HOT=0
        fi
        
        if [ $STEP -eq 2 ]
        then
            if [ $(echo "$ACTUAL_CPU_FREQ_SET < $MAX_CPU_FREQ" | bc -l) -eq 1 ]
            then
                ACTUAL_CPU_FREQ_SET="$(echo "$ACTUAL_CPU_FREQ_SET + $FREQ_DIFF" | bc)"
            else
                MAX_CPU_FREQ=$(echo "$MAX_CPU_FREQ * 1000" | bc -l)
                STEP=3
            fi
        fi
        
        if [ $(echo "$ACTUAL_TEMP < $MIN_TEMP_ROUTINE" | bc -l) -eq 1 ]
        then
            if [ $STEP -eq 3 ] && [ $(echo "$ACTUAL_CPU_FREQ >= $MIN_CPU_FREQ" | bc -l) -eq 1 ]
            then
                if [ $(echo "$READABLE_ACTUAL_CPU_FREQ_SET < $MAX_CPU_FREQ" | bc -l) -eq 1 ]
                then
                    echo "$ACTUAL_CPU_FREQ_SET"
                    ACTUAL_CPU_FREQ_SET="$(echo "$ACTUAL_CPU_FREQ_SET + $FREQ_DIFF" | bc)"
                fi
            fi 
        fi
    fi
        
    value=`echo "$ACTUAL_CPU_FREQ_SET * 1000000" | bc`
    
    sudo cpufreq-set -c 1 -g powersave -u `echo "$value"`
    sudo cpufreq-set -c 2 -g powersave -u `echo "$value"`
    sudo cpufreq-set -c 0 -g powersave -u `echo "$value"`
    sudo cpufreq-set -c 3 -g powersave -u `echo "$value"`
    
    #echo "MIN CPU FREQ : $MIN_CPU_FREQ"
    #echo "MAX CPU FREQ : $MAX_CPU_FREQ"
    #echo "ACTUAL FREQ : $ACTUAL_CPU_FREQ"
    #echo "TEMP : $ACTUAL_TEMP"
    #echo "MIN TEMP ROUTINE : $MIN_TEMP_ROUTINE"
    #echo "CPU_FREQ: $ACTUAL_CPU_FREQ_SET"
    #echo "ACTUAL READABLE CPU FREQ: $READABLE_ACTUAL_CPU_FREQ_SET"
    #echo "STEP : $STEP"
    #echo "HOT : $HOT"
    #echo ""
    sleep $WAIT
done