#!/bin/bash
TEMPS_FILE="/tmp/temp-file"
FREQ_FILE="/tmp/freq-file"
STRESS_CPU_TEST_FILE="/tmp/stress-cpu-file"
MAX_TEMP=60
MIN_CPU_FREQ=1.0
NOMINAL_CPU_FREQ=1.8
MAX_CPU_FREQ=2.9
ACTUAL_CPU_FREQ=$MAX_CPU_FREQ
WAIT=60
FREQ_DIFF=0.1
CORE=4
STEP=1
HOT=0

echo "while true;do a=1;done" > $STRESS_CPU_TEST_FILE
chmod +x $STRESS_CPU_TEST_FILE
$STRESS_CPU_TEST_FILE&

while true
do
    TEMPS="$(inxi -F | grep Sensors)"
    TEMPS="$(echo "$TEMPS" | grep -o -P "[0-9]*\.{1}[0-9]*")"
    CPU="$(inxi -F | grep -A 1 "clock speeds")"
    CPU="$(echo "$CPU" | grep -o -P "\d* MHz")"
    CPU="$(echo "$CPU" | grep -o -P "\d*")"
    
    echo "$CPU" > $FREQ_FILE
    echo "$TEMPS" > $TEMPS_FILE
    
    FREQ1="$(cat $FREQ_FILE | awk 'NR>2{exit}NR>=2')"
    FREQ2="$(cat $FREQ_FILE | awk 'NR>3{exit}NR>=3')"
    FREQ3="$(cat $FREQ_FILE | awk 'NR>4{exit}NR>=4')"
    FREQ4="$(cat $FREQ_FILE | awk 'NR>5{exit}NR>=5')"

    ACTUAL_FREQ="$(echo "($FREQ1 + $FREQ2 + $FREQ3 + $FREQ4) / 4" | bc)"
    CPU_TEMP="$(head -n 1 $TEMPS_FILE)"
    TEMP_LEN=${#CPU_TEMP}
    ACTUAL_TEMP=${CPU_TEMP:0:(TEMP_LEN-2)}
    
    if [ $ACTUAL_TEMP -gt  $MAX_TEMP ]
    then
       if [ $STEP -eq 1 ]
        then
            HOT=1
            ACTUAL_CPU_FREQ="$(echo "$NOMINAL_CPU_FREQ - $FREQ_DIFF" | bc)"
        fi
        
        ACTUAL_CPU_FREQ="$(echo "$ACTUAL_CPU_FREQ - $FREQ_DIFF" | bc)"
    elif [ $ACTUAL_TEMP -lt $MAX_TEMP ]
    then
        if [ HOT -eq 1 ]
        then
            STEP=2
            HOT=0
        fi
        
        if [ $STEP -eq 2 ]
        then
            ACTUAL_CPU_FREQ="$(echo "$ACTUAL_CPU_FREQ + $FREQ_DIFF" | bc)"
        fi
        
    fi
    
    value=`echo "$ACTUAL_CPU_FREQ * 1000000" | bc`
    
    sudo cpufreq-set -c 1 -g powersave -u `echo "$value"`
    sudo cpufreq-set -c 2 -g powersave -u `echo "$value"`
    sudo cpufreq-set -c 0 -g powersave -u `echo "$value"`
    sudo cpufreq-set -c 3 -g powersave -u `echo "$value"`
    
    #echo "$ACTUAL_CPU_FREQ"
    sleep $WAIT
done
